services:
  tiklabchallenge.api:
    image: ${DOCKER_REGISTRY-}tiklabchallengeapi
    build:
      context: .
      dockerfile: TiklabChallenge.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_URLS=https://+:8081
    networks:
      - productnetwork
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticklab-challenge
      ACCEPT_EULA: "Y"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - productnetwork

networks:
  productnetwork:
  
volumes:
  pgdata: